name: Chore / Tech Debt
description: Track refactors, cleanup, maintenance tasks, and technical debt
title: "[Chore]: "
labels: ["chore"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our technical foundation!

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise summary of what needs to be done.
      placeholder: Brief summary of the chore or tech debt...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context / Background
      description: Why does this exist? What led to this debt?
      placeholder: |
        - Historical reasons
        - Previous shortcut or workaround
        - Upstream library change
        - Team growth or process evolution
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Debt Description
      description: What is suboptimal today? What pain does it cause?
      placeholder: |
        Describe what's problematic:
        - Impact on developer velocity
        - Reliability concerns
        - Maintenance burden
        - Performance issues
        - Security risks
    validations:
      required: true

  - type: textarea
    id: approach
    attributes:
      label: Proposed Approach
      description: High-level idea of how the debt will be addressed (not a detailed implementation plan).
      placeholder: Describe the general approach to resolve this...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact if Not Addressed
      description: What happens if we don't do this? What are the risks?
      placeholder: |
        - Performance degradation over time
        - Security vulnerabilities
        - Increased maintenance costs
        - Reduced developer productivity
        - Technical limitations
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Clear, testable conditions for "done".
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this work?
      options:
        - Low
        - Medium
        - High
    validations:
      required: false

  - type: checkboxes
    id: affected_areas
    attributes:
      label: Affected Areas
      description: Which parts of the system are affected? (Select all that apply)
      options:
        - label: CI/CD
        - label: Build system
        - label: Runtime/Application code
        - label: Infrastructure
        - label: Documentation
        - label: Dependencies
        - label: Testing
        - label: Observability/Monitoring
        - label: Security
        - label: Other

  - type: textarea
    id: related
    attributes:
      label: Related Issues / PRs
      description: Link to related issues, PRs, or discussions.
      placeholder: |
        - #123
        - #456
        - https://github.com/org/repo/pull/789
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, logs, or examples here.
      placeholder: Any additional information...
    validations:
      required: false
