name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise summary of the feature you'd like to see.
      placeholder: Brief summary of the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: What alternatives have you considered?
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of this feature? Who would benefit from it?
      placeholder: |
        - Benefit 1
        - Benefit 2
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: willingness
    attributes:
      label: Implementation
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to implement this feature
          required: false
